controller_frequency: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: false

TrajectoryPlannerROS:
   max_vel_x: 0.2
   min_vel_x: 0.1
   max_vel_y: 0.0   
   min_vel_y: 0.0
   max_vel_theta: 0.2
   min_vel_theta: -0.2
   max_rotational_vel: 0.2
   max_in_place_vel: 0.2
   min_in_place_vel_theta: 0.2
   escape_vel: -0.1
   acc_lim_x: 0.4
   acc_lim_y: 0.0   
   acc_lim_theta: 0.7

   holonomic_robot: false
   yaw_goal_tolerance: 0.5 # about 6 degrees
   xy_goal_tolerance: 0.3  # 5 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.4
   gdist_scale: 0.8
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.05
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.0
   sim_granularity: 0.05
   angular_sim_granularity: 0.1
   vx_samples: 8
   vy_samples: 0   
   vtheta_samples: 20
   dwa: false
   simple_attractor: false
   
   
   controller_frequency: 10.0
   planner_patience: 5.0
   controller_patience: 3.0
   planner_frequency: 0.0
   shutdown_costmaps: true
   oscillation_timeout: 5.0
   oscillation_distance: 0.5
   max_planning_retries: 2

