TrajectoryPlannerROS:

 odom_topic: odom
 
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 max_samples: 500
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: False #True
 max_global_plan_lookahead_dist: 3.0
 global_plan_viapoint_sep: -1
 global_plan_prune_distance: 1
 exact_arc_length: False
 feasibility_check_no_poses: 5
 publish_feedback: False
 dwa: False
 
 max_vel_x: 0.2
 min_vel_x: 0.1
 max_vel_y: 0.0   
 min_vel_y: 0.0
 max_vel_theta: 0.2
 min_vel_theta: -0.2
 max_rotational_vel: 0.2
 min_in_place_vel: 0.2
 min_in_place_vel_theta: 0.2
 escape_vel: -0.1
 acc_lim_x: 0.4
 acc_lim_y: 0.0   
 acc_lim_theta: 0.7


 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "line"
   radius: 0.2 # for type "circular"
   line_start: [-0.4, 0.0] # for type "line" #[0.0, 0.0]
   line_end: [0.4, 0.0] # for type "line"
#   front_offset: 0.2 # for type "two_circles"
#   front_radius: 0.2 # for type "two_circles"
#   rear_offset: 0.2 # for type "two_circles"
#   rear_radius: 0.2 # for type "two_circles"
#   vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"


 # GoalTolerance
    
 xy_goal_tolerance: 0.5
 yaw_goal_tolerance: 0.5
 free_goal_vel: False
 complete_global_plan: True
 latch_xy_goal_tolerance: false
 pdist_scale: 0.4
 gdist_scale: 0.8
 meter_scoring: true
   
 # Obstacles
    
 min_obstacle_dist: 0.27 #0.27 # This value must also include our robot's expansion, since footprint_model is set to "line".
 inflation_dist: 0.3
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.5
 obstacle_poses_affected: 15

 dynamic_obstacle_inflation_dist: 0.3
 include_dynamic_obstacles: True 

 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 obstacle_cost_exponent: 4
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1 # must be > 0
 weight_shortest_path: 0
 weight_obstacle: 100
 weight_inflation: 0.2
 weight_dynamic_obstacle: 10 # not in use yet
 weight_dynamic_obstacle_inflation: 0.2
 weight_viapoint: 1
 weight_adapt_factor: 2

 # Homotopy Class Planner

# enable_homotopy_class_planning: True
# enable_multithreading: True
# max_number_classes: 4
# selection_cost_hysteresis: 1.0
# selection_prefer_initial_plan: 0.9 #0.95
# selection_obst_cost_scale: 100.0 #1.0
# selection_alternative_time_cost: False

# roadmap_graph_no_samples: 15
# roadmap_graph_area_width: 5
# roadmap_graph_area_length_scale: 1.0
# h_signature_prescaler: 0.5
# h_signature_threshold: 0.1
# obstacle_heading_threshold: 0.45
# switching_blocking_period: 0.0
# viapoints_all_candidates: True
# delete_detours_backwards: True
# max_ratio_detours_duration_best_duration: 3.0
# visualize_hc_graph: False
# visualize_with_time_as_z_axis_scale: False


# shrink_horizon_backup: True
# shrink_horizon_min_duration: 10
# oscillation_recovery: True
# oscillation_v_eps: 0.1
# oscillation_omega_eps: 0.1
# oscillation_recovery_min_duration: 10
# oscillation_filter_duration: 10
# oscillation_timeout: 5
# max_planning_retries: 5

 sim_time: 1.0
 sim_granularity: 0.05
 angular_sim_granularity: 0.1
 vx_samples: 8
 vy_samples: 0
 vtheta_samples: 20
 dwa: false
 simple_attractor: false



 controller_frequency: 10.0
 planner_patience: 5.0
 controller_patience: 3.0
 planner_frequency: 0.0
 shutdown_costmaps: true
 oscillation_timeout: 1.0
 oscillation_distance: 0.5
 max_planning_retries: 2
