
#---standard pioneer footprint---
#---(in meters)---
#footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]
#footprint: [ [-0.5,-0.35], [0.5,-0.35], [0.5,0.35], [-0.5,0.35] ]
#footprint: [ [-0.5,-0.35], [-0.5,0.35], [0.5,0.35], [0.5,-0.35] ]
footprint: [ [-0.30,-0.25], [-0.30,0.25], [0.30,0.25], [0.30,-0.25] ]

transform_tolerance: 0.2
map_type: costmap

always_send_full_costmap: true

obstacle_layer:
 enabled: true
 obstacle_range: 2.0 #3.0
 raytrace_range: 2.5 #3.5
 inflation_radius: 0.4 #0.2
 track_unknown_space: true #fault
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.2 #0.3  # max. distance from an obstacle at which costs are incurred for planning paths. #0.5

static_layer:
  enabled:              true
  map_topic:            "/map"
 
obstacle_layer_voxel:
  enabled: true
  origin_z: 0.0
  z_resolution: 0.05
  z_voxels: 15
  unknown_threshold: 0
  #mark_threshold: 2
  publish_voxel_map: true
  combination_method: 1
  observation_sources: output_points
  output_points:
    sensor_frame: camera_link
    data_type: PointCloud2
    topic: /camera/depth/points
    marking: true
    clearing: true
    obstacle_range: 1.0 #1.90
    raytrace_range: 1.3
    min_obstacle_height: -0.05
    max_obstacle_height: 0.80
    mark_threshold: 3
    observation_persistence: 2.0
